### ISSUE TITLE
vagrant up failed

### ISSUE THREAD

**Issue by oriceon** [vagrant-ops/vagrantops#1]
```
==> default: TASK: [mysql | Copy .my.cnf File with root Password] **************************
==> default: changed: [127.0.0.1]
==> default:
==> default: TASK: [mysql | Update MySQL Root Password for All root Accounts] **************
==> default: failed: [127.0.0.1] => (item=127.0.0.1) => {"failed": true, "item": "127.0.0.1"}
==> default: msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf h
as the credentials
==> default: failed: [127.0.0.1] => (item=::1) => {"failed": true, "item": "::1"}
==> default: msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf h
as the credentials
==> default: failed: [127.0.0.1] => (item=localhost) => {"failed": true, "item": "localhost"}
==> default: msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf h
as the credentials
==> default:
==> default: FATAL: all hosts have already failed -- aborting
==> default:
==> default: PLAY RECAP ********************************************************************
==> default:            to retry, use: --limit @/home/vagrant/config.retry
==> default:
==> default: 127.0.0.1                  : ok=11   changed=9    unreachable=0    failed=1
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong
```

**Comment by fideloper** [comment]
thanks (it's all really rough still!)

I got that last night but thought the issue was cleared up.

At that point, the .my.cnf file is moved to the vagrant user's home directory. That file contains the database root username and password so the client doesn't need to ask for a user/pass when connecting. (In theory).

**Comment by oriceon** [comment]
And there is a fix for that? How can i get rid of that? I removed mysql and other stuff from config file and still have that error. `FATAL: all hosts have already failed -- aborting`

```
---
- hosts: all
  user: vagrant
  sudo: yes
  roles:
    - server
    - ssl
    - nginx
    - php
```

**Comment by fideloper** [comment]
Not yet. This project isn't really ready yet. You're welcome to play with
the tasks at ansible/roles/mysql/tasks/main.yml to see what might be going
on though! Read about the mysql_user module form Ansible here to see if any
extra options there help: http://docs.ansible.com/mysql_user_module.html

**Comment by fideloper** [comment]
Sorry missed a portion of your question - Editing the config.yml is one step.

But check out the `Vagrantfile` and you'll see it copies those Ansible files the `/home/vagrant/opt` directory. You'll need to `vagrant reload --provision` to get Vagrant to re-copy those files with your changes and then provision.

**Comment by oriceon** [comment]
Sure i checked vagrantfile, and place where local ansible are copied to vm. But every time i destroy and recreate machine but end with same error.

**Comment by fideloper** [comment]
Believe I've fixed this via 2553f1e999216cdf509367f6b7e4e9008fcb09f1

**Comment by oriceon** [comment]
```
==> default: NOTIFIED: [php | Restart PHP-FPM] *********************************************
==> default: FATAL: no hosts matched or all hosts have already failed -- aborting
==> default:
==> default:
==> default: FATAL: all hosts have already failed -- aborting
==> default:
==> default: NOTIFIED: [php | Restart PHP-FPM] *********************************************
==> default: FATAL: no hosts matched or all hosts have already failed -- aborting
==> default:
==> default:
==> default: FATAL: all hosts have already failed -- aborting
==> default:
==> default: PLAY RECAP ********************************************************************
==> default:            to retry, use: --limit @/home/vagrant/config.retry
==> default:
==> default: 127.0.0.1                  : ok=51   changed=41   unreachable=0    failed=1
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Same end of script.

The problem is not from mysql or some task. I guess is something with ansible.

**Comment by fideloper** [comment]
I saw this once and then didn't get it any longer, I'll test it tonight and see if it continues - it fails on PHP-FPM in this case, but I'm unsure why restarting PHP-FPM would cause an issue.

**Comment by fideloper** [comment]
This looks like bug https://github.com/ansible/ansible-modules-core/issues/1170

As a temporary work around, I'm deleting the `/etc/init.d/php-fpm` file:
![image](https://cloud.githubusercontent.com/assets/467411/7874878/55611b1c-057b-11e5-8b37-6a52785f8937.png)

**Comment by oriceon** [comment]
Yap, seems that was from this ansible bug! Now it has successfuly compiled. Thanks.
